export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST'
export const UPDATE_TARGET_CATEGORY = 'UPDATE_TARGET_CATEGORY'

export const UPDATE_POST_LIST = 'UPDATE_POST_LIST'
export const UPDATE_POST_LOADING_STATUS = 'UPDATE_POST_LOADING_STATUS'
export const UPDATE_POST_LIST_ORDER = 'UPDATE_POST_LIST_ORDER'
export const UPDATE_POST_BY_ID = 'UPDATE_POST_BY_ID'
export const UPDATE_TARGET_POST = 'UPDATE_TARGET_POST'

export const UPDATE_COMMENT_LIST = 'UPDATE_COMMENT_LIST'
export const UPDATE_COMMENT_LOADING_STATUS = 'UPDATE_COMMENT_LOADING_STATUS'
export const UPDATE_COMMENT_BY_ID = 'UPDATE_COMMENT_BY_ID'
export const UPDATE_TARGET_COMMENT = 'UPDATE_TARGET_COMMENT'
